import Head from "next/head";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests from "../utils/requests";

export default function Home({ results }) {
  return (
    <div>
      <Head>
        <title>Hulu Next</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://upload.wikimedia.org/wikipedia/commons/e/e4/Hulu_Logo.svg"
        />
      </Head>

      <Header />

      <Nav />

      <Results results={results} />
      <div className=" p-5 flex   justify-center">
        <h2>
          made by 🔥{" "}
          <span>
            <a
              className="text-red-500 no-underline md:hover:underline"
              href="https://github.com/jay75chauhan"
              target="_blank"
            >
              jayChauhan
            </a>
          </span>{" "}
        </h2>
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => res.json());

  return {
    props: {
      results: request.results,
    },
  };
}
